### ISSUE TITLE
Criar as políticas de garantia da qualidade

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#10]
Criar uma Sessão de Políticas **se for necessário** para acomodar as políticas identificadas em formas de artefatos.
- [x] Analisar o processo de GQA para identificar as políticas que devem ser documentadas através do modo mencionado a cima;

Algumas políticas já identificadas:
- [x] Estrutura das Não Conformidades (Essa política será feita nessa issue #7  , pois é muito grande).
- [x] O acompanhamento das não conformidades identificadas será definido como uma política que levará em conta vários aspectos, como: criticidade, tempo, ação e etc.
   - A política deve definir o que será feito se uma não conformidade for encontrada;
   - A política deve definir quem irá acompanhar a não conformidade;
   - A política deve definir a criticidade das não conformidades;
   - A política deve definir um período de tempo para a correção de cada uma;
   - A política deve definir a ação para mitigar a não conformidade;
      - Não temos certeza se a ação pode estar como política ou será definida pela pessoa que irá acompanhar a não conformidade.
- [x] Documentar a justificativa do **processo de preparação de GQA** ser executado apenas uma vez pelas equipes de GQA.

**Comentários com as palavras da Professora:**

Definir no documento de políticas de garantia da qualidade

- Templates que serão usados para auditorias (sejam checklists, entrevistas ou outros formatos)

- Ferramentas que serão utilizadas para documentar os artefatos do processo (drive, excel, word, issues, wiki e etc)

- Como serão realizadas as auditorias e o que será auditado também deve ser registrado dentro das políticas

*** As políticas relacionadas as não conformidades serão realizadas de acordo com a issue #7 , porém deve-se lembrar que elas são um "subproblema" das políticas de garantida da qualidade (que é algo mais geral)

- Explicitar no processo que a não conformidade deve ser acompanhada por um prazo diferente das auditorias. Por exemplo, o prazo para resolver o problema X é dois dias, e não até a próxima auditoria

- Colocar na descrição da atividade do processo: ao registrar a não conformidade, é necessário informar a complexidade dela

**Comment by freemanpivo** [comment]
Senhores, alguém por acaso já começou a escrever as políticas, se sim, podem subi-la? Eu eu o @thiagonf estávamos discutindo e talvez seja necessário documentar nas políticas o fato do "processo de preparação de GQA" ser executado apenas uma única vez pela primeira equipe de GQA (nós).
