### ISSUE TITLE
Renomear o artefato "Resultado Padronizado"

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#11]
Na atividade 3.3 do processo, chamada Registrar resultados, existe uma saída chamada "Resultado Padronizado", o que não deixa muito claro o que é, sugeriu-se trocar para "Resultado Consolidado"

** Deve ser atualizado tanto no diagrama quanto na descrição da atividade do processo

**Comment by maugustoo** [comment]
Essa issue foi fechada pois as atividades que eram para ser feitas nela serão feitas na issue #20
