### ISSUE TITLE
Backlog da Release

### ISSUE THREAD

**Issue by eliseuegewarth** [UnbFeelings/unb-feelings-GQA#119]
Issue relacionada: #71

**Comment by peddrro** [comment]
Nessa iteração 3, acredito não ser necessário realizar essa auditoria, visto que os critérios de aceitação estão mais ligados para o início do Ciclo, onde vê o mapeamento dos épicos/features. Acredito que apenas a auditoria do Backlog Release Refinado seja suficiente.
