### ISSUE TITLE
Mudar o template da descrição de atividades

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#12]
Mudar o template atual que é o seguinte:

<table>
 <tbody>
  <tr>
   <td><b>Descrição</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Papéis</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Entradas</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Saídas</b></td>
   <td>Texto</td>
  </tr>
 </tbody>
</table>

Para:

<table>
 <tbody>
  <tr>
   <td><b>Descrição</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Responsáveis</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Envolvidos</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Entradas</b></td>
   <td>Texto</td>
  </tr>
  <tr>
   <td><b>Saídas</b></td>
   <td>Texto</td>
  </tr>
 </tbody>
</table>

Resumindo: Na descrição das atividades,colocar :
     - Responsáveis
     - Envolvidos
Em substituição aos papéis

**Comment by thiagonf** [comment]
O template foi atualizado e revisado, como pode ser visto no seguinte documento https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Descri%C3%A7%C3%A3o-do-Processo .
