### ISSUE TITLE
Criar issues no repositório unb-feelings-docs

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#13]
@UnbFeelings/gqa
Reportar tudo que impede que nossas atividades sejam realizadas.

**Comment by fabiolamfleury** [comment]
Tendo em vista que as auditorias foram iniciadas e serão criadas issues para não conformidades, não seria melhor fechar essa issue?

**Comment by AllanNobre** [comment]
@fabiolamfleury Por mim, tudo bem.
