### ISSUE TITLE
Definir na wiki as ferramentas que serão utilizadas

### ISSUE THREAD

**Issue by joaopaulonsoares** [UnbFeelings/unb-feelings-GQA#14]
1. Criar documento de ferramentas utilizadas.
   - Dizer como as ferramentas serão utilizadas.

**Comentário com as palavras da professora:**
É necessário deixar documentado as ferramentas que serão utilizadas pelo time de garantia da qualidade, assim como a maneira que cada uma será usada.

**Comment by joaopaulonsoares** [comment]
Ferramentas:
 -  [ ] Wiki do GitHub
 -  [ ] Google Drive (Planilhas, formulários, compartilhamento )
 -  [ ] Zenhub

**Comment by naiieandrade** [comment]
E ai galera, se alguém puder/quiser dar um feedback, vlw flw

**Comment by Rdlenke** [comment]
O how de como o Zenhub será utilizado pode ser encontrado no [documento de estrutura organizacional][estrutura-organizacional],

[estrutura-organizacional]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Estrutura-Organizacional-e-de-Trabalho

**Comment by AllanNobre** [comment]
Revisado e corrigido o "How" de como o ZenHub será usado! Foram acrescentados tbm o "How" das outras ferramentas.
