### ISSUE TITLE
Melhorar a visualização do processo na wiki

### ISSUE THREAD

**Issue by maugustoo** [UnbFeelings/unb-feelings-GQA#16]
- [x] Separar os sub-processos em páginas;
   - Cada página deve ter a foto do sub-processo e a descrição das atividades deste;
- [x] Deve ser colocado no sub-processo onde as próximas equipes de **GQA** entrarão no processo;
- [x] Mudar as descrições de acordo as atualizações feitas no processo;
- [x] Explicitar tarefas e Sub-Processos referentes ao fluxo de trabalho para a Gestão do Conhecimento;
- [x] Explicitar tarefas relacionadas ao processo de auditoria de fato.

# Descrição de atividades

- No subprocesso de executar auditoria, na atividade de reportar pro gerente de projeto, deve-se especificar que: o revisor deve reportar a não conformidade, falar qual a criticidade, prazo para resolver e possível solução
- Na atividade consolidar resultados do ciclo: quantidade de auditorias, quais não conformidades foram encontradas, se foram resolvidas ou não (o mínimo, conseguem pensar em mais algum dado relevante?)
- Na atividade de mudar o time de GQA (não faz parte necessariamente do processo de auditorias, porém será realizado pela equipe)  devem ser descritas as decisões de gerenciamento de conhecimento e afins

OBS: MUDANÇAS NO PROCESSO SERÃO PROVIDAS POR UM PROCESSO DE APOIA QUE FOGE O ESCOPO DA EQUIPE DE GQA;

**Comentários com as Palavras da Professora:**
- Colocar na descrição da atividade do processo: ao registrar a não conformidade, é necessário informar a complexidade dela ;

**Comment by Ronyell** [comment]
Responsáveis:
-----
Processo Geral - @maugustoo 
Subprocesso Executar Auditoria - @joaopaulonsoares 
Subprocesso Planejar Auditorias do Ciclo - @Ronyell
Processo de  Fluxo de Trabalho - @thiagonf e @freemanpivo

**Comment by maugustoo** [comment]
@Ronyell .

**Comment by maugustoo** [comment]
@AllanNobre A atividade consolidar resultados do ciclo do processo geral tem quais entradas?

**Comment by AllanNobre** [comment]
Acredito que nenhuma! Verifica com o resto do time, mas a princípio seriam todos os resultados de tudo durante o Ciclo, inclusive as experiências dos auditores. Daí no processo não dá pra representar direito, aí fica sem entrada. Veja com os demais, pode ser que eu esteja errado.

**Comment by thiagonf** [comment]
Até o presente momento a equipe de qualidade não colocou em execução o processo de fluxo de trabalho, pois o foi necessário uma refatoração significativamente grande em todos os processos da equipe de GQA após uma conversa com a professora. O processo começará a ser executado quando todas as atividades preparatórias anteriores a ele forem concluídas.

**Comment by AllanNobre** [comment]
Atividade já foi revisada! Está OK, foram feitas, somente, pequenas alterações.
