### ISSUE TITLE
Definir critérios de avaliação

### ISSUE THREAD

**Issue by Ronyell** [UnbFeelings/unb-feelings-GQA#19]
- [x] Criar documento "Objetos de Auditoria"
- [x] Listar todos os objetos a serem auditados
- [x] Definir critérios de avaliação para cada objeto auditado 

@UnbFeelings/gqa

**Comment by AllanNobre** [comment]
Divisão de Trabalho:

@AllanNobre
* Lista informal de requisitos
* Requisitos
* Backlog

@thiagonf 
* Backlog Validado
* Backlog Refinado
* Backlog da Release

@Ronyell 
* Planejamento de Treinamentos
* Backlog da Sprint
* Testes de Software

@Rdlenke 
* Incremento de software
* Backlog da Release Refinado
* Relatório da Retrospectiva

@maugustoo 
* Plano de medição
* Plano de medição Refinado
* Métricas de Processo

@joaopaulonsoares 
* Métricas de Código
* Documentação da análise das Métricas
* Relatório de Desempenho

@JonathanRufino 
* Relatório Final
* Melhoria da qualidade do processo ou do produto
* Processo do ciclo de desenvolvimento

@igor-gme 
* Subprocesso Requisitos
* Subprocesso Desenvolvimento
* Medição e Análise

**Comment by Ronyell** [comment]
@Ronyell

## Criérios

### Planejamento de Treinamentos
  - O planejamento de treinamentos deve existir.
  - O treinamento deve ter o responsável definido.
  - O treinamento deve ter data definida.

### Backlog da Sprint
  - O backlog da Sprint deve existir.
  - O backlog da sprint deve conter as histórias de usuário da sprint em questão.
  - As histórias de usuário devem ser escritas em voz de usuário. (Eu, como ..., desejo ... para ...).
  - As histórias de usuário devem ter critérios de aceitação.
  - As histórias de usuário devem estar pontuadas.
  - As histórias de usuário devem ser referentes a _features_ levantadas.
  - As histórias de usuário devem ser alocadas aos integrantes de times.

### Testes de Software
  - O

**Comment by Rdlenke** [comment]
## Incremento de Software
- A sprint deve ter sido planejada.
- Todas as histórias da sprint devem ter sido concluídas.
- Todas as histórias da sprint devem ter sido integradas na branch principal do projeto.
- A integração contínua do projeto deve estar funcional no último commit da release.
- O projeto deve estar funcional na branch principal.

## Backlog da Release Refinado
- A sprint deve ter sido finalizada.
- As histórias que foram concluídas devem ser identificadas e documentadas.
- As histórias que não foram concluídas devem ser identificadas e documentadas.
- O quanto de uma história não concluída foi realizado deve ser documentado.
- Os motivos pelos quais uma história não foi concluída devem ser documentados.
- As dívidas para próximas sprints devem ser identificadas e documentadas.
- Os bugs conhecidos devem ser identificados e documentados.
- O Backlog da release deve ser replanejado/repristinizado.

## Relatório da Retrospectiva
- A sprint deve ter sido finalizada.
- A revisão deve ter sido finalizada.
- Os pontos negativos da sprint estão identificados.
- Os pontos positivos da sprint estão identificados.
- As propostas de melhoria para as próximas sprints estão identificadas e documentadas.

**Comment by joaopaulonsoares** [comment]
### Métricas de Código

* As métricas devem ser coletadas na periocidade previamente planejada.
* Todas as métricas previstas devem ser coletadas
   * Porcentagem de código testado
   * Complexidade Ciclomática
   * Segue folha de estilo
   * Duplicação de código
   * % de endpoints testados
   * Nº Linhas comentadas por linhas de código
* Essa coleta deve ser realizada pela equipe de processo

### Documentação da análise das Métricas
* A documentação da análise das métricas deve ser realizada após a coleta das métricas.
* Esse plano deve ser realizada pela equipe de processo
* Esse plano deve ser realizado no período planejado.
* As métricas com valor satisfatório devem ser apresentadas.
* As métricas com valor insatisfatório devem ser apresentadas.

### Relatório de Desempenho
*  Um relatório especificando quais foram as métricas que apresentaram valor satisfatório, assim como aquelas que ficaram abaixo do valor esperado devem ser gerado.
* Esse relatório deve ser realizada pela equipe de processo.
* Esse relatório deve ser realizado no período planejado.
* Este relatório deve ser utilizado como insumo para melhoria da qualidade do processo ou do produto.

**Comment by maugustoo** [comment]
## Critérios

### Plano de medição

- [ ] O plano de medição deve existir
- [ ] O plano de medição deve seguir o GQM
- [ ] O plano de medição deve conter os objetivos estratégicos
- [ ] O plano de medição deve conter as questões
- [ ] O plano de medição deve conter as análises do que será medido
- [ ] O plano de medição deve conter o planejamento das coletas

###Plano de medição Refinado

- [ ] O plano de medição refinado deve existir
- [ ] O plano de medição refinado deve conter as métricas que serão utilizadas
- [ ] O plano de medição refinado deve conter as técnicas utilizadas para cada métrica
- [ ] O plano de medição refinado deve conter os indicadores referentes às métricas.

###Métricas de Processo

- [ ] Devem ser selecionado as métricas que serão coletadas
- [ ] Deve ser definido as técnicas de coleta para cada métrica
- [ ] O documento de métricas de processo deve existir
- [ ] A coleta de métricas deve ser feita

**Comment by JonathanRufino** [comment]
## Relatório Final
- O relatório deve existir
- O relatório deve apresentar o resultado das métricas coletadas
- O relatório deve apresentar a evolução histórica das métricas
- As métricas devem estar relacionadas com os indicadores definidos

## Melhoria da qualidade do processo ou do produto
- 

## Processo do ciclo de desenvolvimento
- Todas as atividades devem ter sido realizadas
- Os artefatos de entrada devem existir
- Os artefatos de saída devem existir
- Os artefatos de entrada devem possuir conteúdo suficiente para auxiliar na execução das tarefas que os utilizam

**Comment by thiagonf** [comment]
Backlog Validado
 - [ ]   Existe o backlog?
 - [ ]   O backlog foi derivado a partir da lista de necessidades do cliente?
 - [ ]   O backlog foi validado com o cliente?
 - [ ]   O backlog foi aprovado

- Técnicas que serão utilizadas checklist e entrevista

Backlog Refinado
 - [ ]   Foram levantados os requisitos?
 - [ ]   O cliente foi expôs os requisitos?

- Técnicas que serão utilizadas checklist e entrevista

Backlog da Release
 - [ ]   Foram mapeados épicos?
 - [ ]   Foram mapeados features?
 - [ ]   O cliente validou os épicos?
 - [ ]   O cliente validou os features?

- Técnicas que serão utilizadas checklist e entrevista

**Comment by AllanNobre** [comment]
@AllanNobre
## **Critérios**

### Lista informal de requisitos
* A Lista Informal de Requisitos deve existir;
* Devem existir requisitos escritos em linguagem informal;
* Deve ter acontecido uma interação com o cliente;
* A equipe deve ter entendido o problema do cliente;
* A equipe deve ter entendido as necessidades do cliente;
* Deve ter sido utilizada alguma técnica de elicitação;
* Os Requisitos devem ter sido elicitados.

### Requisitos
* Os Requisitos devem existir;
* A equipe de desenvolvimento deve ter sido reunida para analisar os requisitos;
* O cliente deve ter participado da reunião para analisar os requisitos;
* Os requisitos devem ter sido analisados pelos membros da equipe.

### Backlog
* O Backlog deve existir;
* Os conhecimentos da fase de elicitação devem ter sido lapidados;
* Os conhecimentos lapidados da fase de elicitação devem ter sido documentados no BackLog;
* Todas as features do projeto devem ter sidos definidas;
* Deve existir um documento que contém informações a respeito dos Requisitos do Sistema;
* A equipe de desenvolvimento deve ter executado uma atividade que gerou esse Backlog.

**Comment by igor-gme** [comment]
### Critérios

## Subprocesso Requisitos
* Houve reunião com o cliente para elicitar os requisitos?
* Existe uma lista informal de requisitos, derivadas dos requisitos elicitados juntamente com o cliente?
* Qual(is) técnica(s) foram utilizadas para entender as necessidades do cliente?
* Existe um documento registrando os requisitos, derivado da análise dos requisitos?
* Como foi documentado os requisitos do sistema?
* Foi feita uma reunião com o cliente para validar os requisitos? 
* As respostas foram condizentes com o que foi definido no processo?

## Subprocesso Desenvolvimento
* Ocorreu uma reunião com a equipe para o planejamento da Sprint?
* O Backlog da Sprint foi priorizado no planejamento da Sprint?
* Teve algum registro dos participantes presentes no planejamento da Sprint?
* O código gerado durante a etapa de foi desenvolvido foi testado?
* O Daily Meeting foi realizado diariamente?
* Teve algum registro dos participantes presentes no Daily Meeting?
* Houve retrospectiva da Sprint?
* A retrospectiva da Sprint foi realizada com os membros da equipe?
* As respostas foram condizentes com o que foi definido no processo?

## Medição e Análise
* Existe um plano de medição derivado do planejamento das medições?
* Como foi definido o que será medido?
* Qual(is) a(s) métrica(s) selecionadas para serem medidas?
* Qual(is) técnica(s) foram definidas para coletar as métricas?
* Houve reunião com a equipe de desenvolvimento para a coleta das métricas?
* Como foi feita a coleta das métricas de processo?
* Como foi feita a coleta das métricas de código?
* Como ocorre a análise das métricas colhidas(código e processo)?
* Como é gerado o relatório especificando as métricas satisfatórias e não satisfatórias?
* As respostas foram condizentes com o que foi definido no processo?

**Comment by AllanNobre** [comment]
Os critérios do @AllanNobre, @igor-gme , @Ronyell  e @thiagonf já foram documentadas, alterações devem ser feitas no [documento](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria) e não mais na issue.

**Comment by igor-gme** [comment]
Os critérios do @Rdlenke, @joaopaulonsoares, @maugustoo e @JonathanRufino já foram documentadas, alterações devem ser feitas no [documento](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria) e não mais na issue.
