### ISSUE TITLE
Aplicar atualizações de FeedBack no Processo

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#20]
Atualizações:
- [x] Renomear o artefato Resultado Padronizado para Resultado Consolidado;
- [x] Reorganizar o subprocesso que lida com as não conformidades;
- [x] Criar atividade de **Definir Critérios de Avaliação** (Após definir objetos de Avaliação);
   - Gerar artefato de Critérios de Avaliação;
- [x] Arrumar no último sub-Processo a forma como serão tratadas as inconformidades do ciclo (Atividade ou Sub-Processo menor);
- [x] Criar atividade para Definir ferramentas;
   - Gerar artefato de ferramentas;
- [x] Tirar ferramenta de dentro do Sub-Processo Detalhar;
- [x] Analisar Processo, Critérios de Avaliação, Definir Ferramentas;
- [x] Eliminar tarefas desnecessárias do Processo;

OBS: MUDANÇAS NO PROCESSO SERÃO PROVIDAS POR UM PROCESSO DE APOIA QUE FOGE O ESCOPO DA EQUIPE DE GQA;

**Comentário com as palavras da professora:**
Na atividade 3.3 do processo, chamada Registrar resultados, existe uma saída chamada "Resultado Padronizado", o que não deixa muito claro o que é, sugeriu-se trocar para "Resultado Consolidado"

** Deve ser atualizado tanto no diagrama quanto na descrição da atividade do processo

- Explicitar no processo que a não conformidade deve ser acompanhada por um prazo diferente das auditorias. Por exemplo, o prazo para resolver o problema X é dois dias, e não até a próxima auditoria

- Colocar na descrição da atividade do processo: ao registrar a não conformidade, é necessário informar a complexidade dela

**Comment by AllanNobre** [comment]
Está tudo feito, só falta arrumar o último sub-Processo. Aparentemente ele irá desaparecer e somente 3 das suas atividades irão permanecer soltas no processo de GQA macro (Identificar Sugestões de Melhoria, Avaliar Resultados Obtidos e Realizar Reunião de Feedback).

**Comment by freemanpivo** [comment]
@AllanNobre , ficou decidido o que na aula? A gente coloca ela como uma única atividade mesmo?

**Comment by AllanNobre** [comment]
@freemanpivo, Nós colocamos já como uma só atividade! Com isso, essa atividade está concluída!
