### ISSUE TITLE
Separar Processo de Trabalho (GC) de GQA

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#22]
- [x] Separar as imagens do Processo;
- [x] Subir as imagens pra WIki;

**Comment by Rdlenke** [comment]
O processo de fluxo de trabalho não tem imagens, correto?

**Comment by Ronyell** [comment]
@Rdlenke Tem, ainda não foi colocado na página mas já está no git. Esse é o processo que o Allan chamou de "processo de preparação para o GQA."

**Comment by Rdlenke** [comment]
@Ronyell Ok. Vou desmarcar e voltar pra doing.
