### ISSUE TITLE
[Template Não Conformidade] Código sem testes

### ISSUE THREAD

**Issue by JonathanRufino** [UnbFeelings/unb-feelings-GQA#23]
### Descrição

O código desenvolvido não possui testes implementados para garantir o seu comportamento e consequentemente a qualidade do código

#### Recomendações
Configurar integração contínua para não aceitar pull requests com cobertura de código inferior a atual

### Detalhes

**Data de Identificação:** 07/04/2018
**Autor:** Jonathan Rufino
**Tipo:** Implementação
**Prazo:** 25/04/2018

**Comment by AllanNobre** [comment]
Template revisado! Deve ser seguido sempre que uma não conformidade for identificada.
