### ISSUE TITLE
Definir técnicas para cada objeto de auditoria

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-GQA#24]
Definir quais vão ser as técnicas utilizadas para cada objeto de auditoria existente. Estas técnicas podem ser checklists, entrevistas, ou alguma forma de verificação de maneira que, com elas, seja possível produzir os documentos que irão compor o feedback da auditoria.

[Atividade no processo](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Fluxo-de-Trabalho#15-definir-t%C3%A9cnicas-para-cada-objeto-de-auditoria).

**Comment by maugustoo** [comment]
## Técnicas

### Plano de medição

- Checklist
- Entrevista

### Plano de medição Refinado


- Checklist
- Entrevista

### Métricas de Processo

- Checklist
- Entrevista

**Comment by Ronyell** [comment]
## Técnicas
### Planejamento de Treinamentos
 - Checklist
 - Entrevista
  
### Backlog da Sprint
 - Checklist
 - Entrevista

### Testes de Software
 - Checklist
 - Entrevista

**Comment by igor-gme** [comment]
## Técnicas
### Subprocesso Requisitos
 - Questionário
 - Entrevista
  
### Subprocesso Desenvolvimento
 - Questionário
 - Entrevista

### Medição e Análise
 - Questionário
 - Entrevista

**Comment by Rdlenke** [comment]
## Técnicas
### Incremento de Software

- Entrevista

### Backlog da Release Refinado

- Checklist

### Relatório da Retrospectiva

- Checklist

**Comment by thiagonf** [comment]
**Backlog Validado**

- Técnicas que serão utilizadas checklist e entrevista

**Backlog Refinado**

- Técnicas que serão utilizadas checklist e entrevista

**Backlog da Release**


- Técnicas que serão utilizadas checklist e entrevista

**Comment by JonathanRufino** [comment]
## Técnicas

### Relatório Final

- Checklist

### Melhoria da qualidade do processo ou do produto

- Entrevista

### Processo do ciclo de desenvolvimento

- Checklist
- Entrevista

**Comment by AllanNobre** [comment]
## Técnicas 
 
### Lista informal de requisitos 
- Checklist 
- Entrevista

### Requisitos
- Checklist 
- Entrevista
 
### Backlog
- Checklist 
- Entrevista

**Comment by AllanNobre** [comment]
As técnicas do @AllanNobre, @igor-gme , @Ronyell  e @thiagonf já foram documentadas, alterações devem ser feitas no [documento](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria) e não mais na issue.

**Comment by igor-gme** [comment]
As técnicas do @Rdlenke, @joaopaulonsoares, @maugustoo e @JonathanRufino já foram documentadas, alterações devem ser feitas no [documento](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria) e não mais na issue.
