### ISSUE TITLE
Analisar Processo e Artefatos

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-GQA#25]
Analisar o processo definido pela [equipe de processo][e-processo] para identificar quais partes deste processo e quais artefatos serão auditados pela equipe GQA. Eu recomendo que a definição destes artefatos e processos tenham algum embasamento, seja ele por conta dos objetivos organizacionais, qualidade do produto, ou porque é necessário para a disciplina.

[e-processo]:https://github.com/UnbFeelings/unb-feelings-docs

**Comment by Rdlenke** [comment]
Uma dificuldade na definição de quais serão os objetos e processos auditados é o fato de que a nossa organização não tem objetivos organizacionais bem definidos. No entanto, já que estamos atrasados, eu procurei identificar alguns possíveis candidatos pra auditoria.

---

Possíveis candidatos para a auditoria:
## Desenvolvimento

[Subprocesso de requisitos da equipe de desenvolvimento][requisitos]: Ter os requisitos corretos é ideal para qualquer processo de desenvolvimento, evitando atrasos, custos adicionais, e a entrega de um produto que não corresponde às expectativas do cliente. [Leffingwell, 2011][leffingwell]

 Por estes motivos, talvez seja interessante auditar a elicitação de requisitos do projeto. No entanto, talvez essa auditoria não seja tão relevante, já que os requisitos já foram bastante detalhados pelo cliente, e talvez não existam muitas iterações para a confirmação dos requisitos.

Caso seja auditado, acredito que o objetivo deve ser verificar a existência da [Lista Informal de Requisitos][lista-informal]. Também é necessário procurar indícios de que a validação com o cliente foi feita para que exista o [Backlog Validado][backlog-validado].

Provavelmente um checklist para verificar qual é o conteúdo obrigatório em cada documento será necessário.

Dúvida: O backlog que é resultado da fase de requisitos do processo de desenvolvimento é um backlog de requisitos avulsos, ou já estão nivelados em épicos?

---
[Atividade de Planejar Release][planejar-release]: A atividade de planejamento da release compreende um aspecto relevante do desenvolvimento, já que seu objetivo é derivar, dos épicos elicitados, as features necessárias para que sejam entregues. Estas features compreendem às funcionalidades que serão implementadas com histórias de usuário. 

O resultado desta atividade é o backlog da release, que, eu acho (não consegui encontrar a descrição caso este documento é por iterações ou ciclos, talvez tenha procurado de maneira incorreta) compreende as features que serão implementadas em uma iteração do projeto. Este documento pode ser auditado, provavelmente com o uso de um checklist que nos permite verificar a rastreabilidade dos requisitos.

Dúvida: existem outros artefatos que talvez sejam gerados nesta atividade. O plano de auditorias, que é nosso, ou seja, não será auditado, e o plano de treinamentos. Talvez seja importante auditar este artefato também. No entanto, **não acredito que haverá tempo para treinamentos**.

--

[Subprocesso Desenvolvimento][sub-desenvolvimento]: Acho que é lógico que o processo de desenvolvimento seja auditado, já que estamos trabalhando com o ágil e queremos entregar releases periódicas. Na minha visão, o objetivo das auditorias deste subprocesso é garantir que a equipe está tentando aumentar a qualidade do produto, com testes unitários, e que está realizando a comunicação de maneira correta, com o daily meeting. Também podemos auditar o próprio incremento de software, de acordo com o número de histórias concluídas ou algo assim, já que o incremento é a saída deste subprocesso.

A auditoria dos testes unitários pode ser feita com o uso de alguma ferramenta de análise, que provavelmente já está configurada. No caso, acredito que podemos usar a cobertura atual como limite para este tipo de auditoria: a cobertura nunca pode diminuir.

No caso das dailys, eu tenho dificuldade em imaginar como vamos auditar, já que ela é uma atividade sem saídas.

Dúvida: Existem dois sub processos de requisitos na "área" de desenvolvimento. Um processo de requisitos antes do planejamento da release, e um depois, dentro do subprocesso de desenvolvimento. No entanto, ambos linkam pra mesma descrição, então eu não fui capaz de diferenciar quais seriam as diferenças (provavelmente no nível dos requisitos, mas não está especificado).

[lista-informal]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2211-elicitar-requisitos
[backlog-validado]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2215-validar-requisito
[backlog-da-release]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint
[planejar-release]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2012-planejar-release
[requisitos]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2011-requisitos-

**Comment by Rdlenke** [comment]
# Desenvolvimento
## Subprocesso Requisitos
- [Lista informal de requisitos][lista-informal]
- [Requisitos][requisitos]
- [Backlog][backlog]
- [Backlog Validado][backlog-validado]
- [Backlog Refinado][backlog-refinado] -> Nem sempre irá ocorrer.

_O último artefato do subprocesso de requisitos da área de desenvolvimento é o Backlog Refinado, mas no processo geral da área, é o Backlog do Produto. Estou assumindo que são iguais_

--
## Atividade Planejar Release
- [Backlog da Release][planejar-release]
- [Planejamento de Auditorias][planejar-release] -> Nosso, provavelmente não será auditado.
- [Planejamento de Treinamentos][planejar-release]

--
## Subprocesso Desenvolvimento
_Dentro deste subprocesso aparece novamente o subprocesso de requisitos. Eu achei que eles eram pra níveis diferentes, mas no processo da organização ambos apontam pra mesma descrição._
_Além disso, o backlog da release tá saindo deste subprocesso de requisitos, ao invés de sair da atividade de Planejar Release._

- [Backlog da Sprint][planejar-sprint]
- [Testes de Software][testar]
- [Incremento de software][desenvolver]
- [Backlog da Release Refinado][revisar]
- [Relatório da Retrospectiva][retrospectiva]

_Há uma inconsistência aqui. Na imagem eles chamam de "Backlog da Release Refinado" o resultado da revisão, mas na descrição chamam de "Backlog da Sprint Refinado"._

[lista-informal]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2211-elicitar-requisitos
[requisitos]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2212-analisar-requisitos
[backlog]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2214-documentar-requisitos
[backlog-validado]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2215-validar-requisito
[backlog-refinado]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2213-refinar-requisitos
[planejar-release]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2012-planejar-release
[planejar-sprint]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2112-planejar-sprint
[revisar]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2114-revisar
[testar]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2114-testar
[desenvolver]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2113-desenvolver
[retrospectiva]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2115-realizar-retrospectiva-

**Comment by Ronyell** [comment]
# Medição e Análise
----

- [Plano de medição][Plano de medição]
- [Plano de medição Refinado][Plano de medição Refinado]
- [Métricas de Processo][Métricas de Processo]
- [Métricas de Código][Métricas de Código]
- [Documentação da análise das Métricas][Documentação da análise das Métricas]
- [Relatório de Desempenho][Relatório de Desempenho]
- [Relatório Final][Relatório Final]
- [Melhoria da qualidade do processo ou do produto][Melhoria da qualidade do processo ou do produto]

_O plano de medição refinado  é uma evolução do plano de medição, será necessário consultar o histórico de modificações no documento.._ 

_**Sobre o Processo**_

 _É sempre necessário retornar à atividade de planejar medição e criar um plano de medição após cada iteração?_

_Nas atividades Definir medições, Coletar métricas do processo e Coletar Métricas do Código  existe a tarefa de "selação de métricas", creio que significam coisas diferentes._



[Plano de medição]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#311-planejar-medi%C3%A7%C3%B5es
[Plano de medição Refinado]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#312-atividade-definir-medi%C3%A7%C3%B5es
[Métricas de Processo]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#313-atividade-coletar-m%C3%A9tricas-do-processo
[Métricas de Código]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#314-atividade-coletar-m%C3%A9tricas-do-c%C3%B3digo
[Documentação da análise das Métricas]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#315-atividade-analisar-m%C3%A9tricas
[Relatório de Desempenho]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#316-atividade-gerar-relat%C3%B3rio
[Relatório Final]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#317-atividade-relat%C3%B3rio-final-de-medi%C3%A7%C3%A3o
[Melhoria da qualidade do processo ou do produto]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#316-atividade-a%C3%A7%C3%A3o-referente-%C3%A0-valor-de-m%C3%A9trica-insatisfat%C3%B3rio

**Comment by AllanNobre** [comment]
Revisado! Objetos de Auditoria estão Ok.
