### ISSUE TITLE
Criar templates de documentação

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#26]
Deve-se identificar quais documentações necessitam de templates para que possam ser criados, como: Resultados das Auditoria, Documentação do Checklist dentro do resultado da Auditoria, Documentação da Entrevista dentro do resultado da Auditoria, entre outros.

[Atividade no processo](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Fluxo-de-Trabalho#17-criar-templates-de-documenta%C3%A7%C3%A3o).

**Comment by maugustoo** [comment]
## Técnicas

### Plano de medição - Checklist

- [ ] O plano de medição existe?
- [ ] O plano de medição está seguindo o GQM?
- [ ] O plano de medição contêm os objetivos estratégicos?
- [ ] O plano de medição contêm as questões derivadas de cada objetivo?
- [ ] O plano de medição contêm as análises do que será medido?
- [ ] O plano de medição contêm o planejamento das coletas?

### Plano de medição Refinado - Checklist

- [ ] O plano de medição existe?
- [ ] O plano de medição refinado contêm as métricas que serão utilizadas para cada questão?
- [ ] O plano de medição refinado contêm as técnicas utilizadas para cada métrica?
- [ ] O plano de medição refinado contêm os indicadores referentes às métricas?

### Métricas de Processo - Checklist

- [ ] As métricas a serem medidas foram selecionadas?
- [ ] As técnicas de coleta para cada métrica foram definidas?
- [ ] As métricas foram coletadas?
- [ ] O documento de métricas do processo foi criado?

**Comment by AllanNobre** [comment]
Documentos identificados para terem template:
- [ ] Checklist;
- [ ] Entrevista;
- [ ] Resultado da Auditoria;
- [ ] Análise do Ciclo.
