### ISSUE TITLE
Ajustar descrições

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#28]
- [x] Ajustar descrição da atividade de Templates;
- [x] Ajustar descrição da atividade de Preparar auditoria;

Deve-se ajustar estas descrições para deixar mais claro quais templates serão criados e o que será feito na preparação da auditoria, que será a criação do Checklist/Entrevista baseado no template deles e a utilização de um desses caso já tenha sido criado para o mesmo Objeto de Auditoria, já que estará armazenado no resultado da Auditoria no Git.

**Comment by maugustoo** [comment]
@AllanNobre Eu mexi ontem na atividade de preparação. Hoje dou uma ajustada final pra sanar a issue.

**Comment by maugustoo** [comment]
Adicionei algumas informações nas atividades para deixar mais claro as atividades de criação de template e que os insumos necessários para as técnicas de auditoria, como checklists e entrevistas, serão confeccionados na preparação da auditoria.

[Atividade de preparação da auditoria](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Sub-Processo-Executar-Auditoria#21-preparar-execu%C3%87%C3%83o-da-auditoria)
[Atividade de criação de templates](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Fluxo-de-Trabalho#17-criar-templates-de-documenta%C3%A7%C3%A3o)
