### ISSUE TITLE
Estimar quantidade de auditorias

### ISSUE THREAD

**Issue by Ronyell** [UnbFeelings/unb-feelings-GQA#29]
Nesta atividade, é considerada a lista dos objetos a serem auditados, para definir quantas auditorias serão necessárias para atender tal demanda. Contribuindo na criação do documento de descrição das auditorias planejadas.

**Comment by Ronyell** [comment]
# Objetos Selecionados

1. Backlog da Sprint
2. Testes de Software
3. Incremento de software
4. Backlog da Release Refinado
5. Relatório da Retrospectiva
6. Plano de medição
7. Plano de medição Refinado
8. Métricas de Processo
9. Métricas de Código
10. Documentação da análise das Métricas
11. Relatório de Desempenho
12. Relatório Final
13. Melhoria da qualidade do processo ou do produto
14. Processo do ciclo de desenvolvimento
15. Subprocesso Requisitos
16. Subprocesso Desenvolvimento
17. Medição e Análise

**Comment by AllanNobre** [comment]
De acordo com a análise de dificuldades, serão cerca de 24 auditorias para este ciclo que vai do dia 12/04 ao dia 24/04.
