### ISSUE TITLE
Planejar as auditorias do ciclo 2

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#31]
- [x] Alocar datas;
- [x] Alocar recursos;
- [x] Alocar objetos;
- [x] Criar documento de planejamento (Data do Ciclo);
   - [x] Id da issue da auditoria;
   - [x] Data da auditoria;
   - [x] Objeto da auditoria;
   - [x] Auditor da auditoria;

**Comment by Rdlenke** [comment]
Roger: Objeto 1 até objeto 8.
Allan: Objeto 9 até objeto 16.
Igor: Objeto 17 até objeto 24.

**Comment by Rdlenke** [comment]
| ID da Issue | Data da Auditoria | Auditor | Objeto de Auditoria |
|:------------------------:|:-------------------------:|:-----------------:|:-----------------:|
| [#ISSUE][#ISSUE] | 13/04/2018 | [@AllanNobre](https://github.com/AllanNobre) | [Lista informal de Requisitos][Lista informal de Requisitos] |
| [#ISSUE][#ISSUE] | 13/04/2018  | [@AllanNobre](https://github.com/AllanNobre) | [Requisitos][Requisitos] |
| [#ISSUE][#ISSUE] | 14/04/2018 | [@thiagonf](https://github.com/thiagonf) | [Backlog Validado][Backlog Validado] |
| [#ISSUE][#ISSUE] | 15/04/2018 | [@thiagonf](https://github.com/thiagonf) | [Backlog Refinado][Backlog Refinado] |
| [#ISSUE][#ISSUE] | 16/04/2018 |[@Ronyell](https://github.com/Ronyell)| [Planejamento de Treinamentos][Planejamento de Treinamentos] |
| [#ISSUE][#ISSUE] | 16/04/2018 |[@Ronyell](https://github.com/Ronyell)| [Backlog da Sprint][Backlog da Sprint] |
| [#ISSUE][#ISSUE] | 17/04/2018 | [@naiieandrade](https://github.com/naiieandrade) | [Backlog][Backlog] |
| [#ISSUE][#ISSUE] | 17/04/2018 | [@naiieandrade](https://github.com/naiieandrade) | [Backlog da Release][Backlog da Release] |




[Lista informal de Requisitos]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#lista-informal-de-requisitos
[Requisitos]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#requisitos
[Backlog Validado]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-validado
[Backlog Refinado]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-refinado
[Planejamento de Treinamentos]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#planejamento-de-treinamentos
[Backlog da Sprint]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-da-sprint
[Backlog]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog
[Backlog da Release]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-da-release

**Comment by igor-gme** [comment]
## 1. Planejamento

| ID da Issue | Data da Auditoria | Auditor | Objeto de Auditoria |
|:------------------------:|:-------------------------:|:-----------------:|:-----------------:|
| [#ISSUE][#ISSUE] | 20/04/2018 | [@joaopaulonsoares](https://github.com/joaopaulonsoares) | [Documentação da análise das Métricas][Documentação da análise das Métricas] |
| [#ISSUE][#ISSUE] | 20/04/2018 |[@joaopaulonsoares](https://github.com/joaopaulonsoares)| [Relatório de Desempenho][Relatório de Desempenho] |
| [#ISSUE][#ISSUE] | 23/04/2018 |[@JonathanRufino](https://github.com/JonathanRufino)| [Relatório Final][Relatório Final] |
| [#ISSUE][#ISSUE] | 22/04/2018 |[@JonathanRufino](https://github.com/JonathanRufino)| [Melhoria da qualidade do processo ou do produto][Melhoria da qualidade do processo ou do produto] |
| [#ISSUE][#ISSUE] | 21/04/2018 |[@freemanpivo](https://github.com/freemanpivo)| [Processo do ciclo de desenvolvimento][Processo do ciclo de desenvolvimento] |
| [#ISSUE][#ISSUE] | 22/04/2018 | [@freemanpivo](https://github.com/freemanpivo) | [Subprocesso Requisitos][Subprocesso Requisitos] |
| [#ISSUE][#ISSUE] | 21/04/2018 | [@fabiolamfleury](https://github.com/fabiolamfleury) | [Subprocesso Desenvolvimento][Subprocesso Desenvolvimento] |
| [#ISSUE][#ISSUE] | 21/04/2018 | [@fabiolamfleury](https://github.com/fabiolamfleury) | [Medição e Análise][Medição e Análise] |

[#ISSUE]:https://

[Documentação da análise das Métricas]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#documenta%C3%A7%C3%A3o-da-an%C3%A1lise-das-m%C3%A9tricas

[Relatório de Desempenho]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#relat%C3%B3rio-de-desempenho

[Relatório Final]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#relat%C3%B3rio-final

[Melhoria da qualidade do processo ou do produto]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#melhoria-da-qualidade-do-processo-ou-do-produto

[Processo do ciclo de desenvolvimento]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#processo-do-ciclo-de-desenvolvimento

[Subprocesso Requisitos]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#subprocesso-requisitos

[Subprocesso Desenvolvimento]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#subprocesso-desenvolvimento

[Medição e Análise]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#medi%C3%A7%C3%A3o-e-an%C3%A1lise

**Comment by AllanNobre** [comment]
## 1. Planejamento

| ID da Issue | Data da Auditoria | Auditor | Objeto de Auditoria |
|:------------------------:|:-------------------------:|:-----------------:|:-----------------:|
| [#ISSUE][#ISSUE] | 17/04/2018 | [@Matheusss03](https://github.com/Matheusss03) | [Testes de Software][Testes de Software] |
| [#ISSUE][#ISSUE] | 17/04/2018 | [@Matheusss03](https://github.com/Matheusss03) | [Incremento de Software][Incremento de Software] |
| [#ISSUE][#ISSUE] | 18/04/2018 | [@rdlenke](https://github.com/Rdlenke) | [Backlog da Release Refinado][Backlog da Release Refinado] |
| [#ISSUE][#ISSUE] | 18/04/2018 | [@rdlenke](https://github.com/Rdlenke) | [Relatório da Retrospectiva][Relatório da Retrospectiva] |
| [#ISSUE][#ISSUE] | 18/04/2018 | [@maugustoo](https://github.com/maugustoo) | [Plano de medição][Plano de medição] |
| [#ISSUE][#ISSUE] | 19/04/2018 | [@maugustoo](https://github.com/maugustoo) | [Plano de medição Refinado][Plano de medição Refinado] |
| [#ISSUE][#ISSUE] | 19/04/2018 | [@igor-gme](https://github.com/igor-gme) | [Métricas de Processo][Métricas de Processo] |
| [#ISSUE][#ISSUE] | 20/04/2018 | [@igor-gme](https://github.com/igor-gme) | [Métricas de Código][Métricas de Código] |

[#ISSUE]:https://
[Testes de Software]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#testes-de-software
[Incremento de Software]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#incremento-de-software
[Backlog da Release Refinado]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-da-release-refinado
[Relatório da Retrospectiva]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#relat%C3%B3rio-da-retrospectiva
[Plano de medição]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#plano-de-medi%C3%A7%C3%A3o
[Plano de medição Refinado]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#plano-de-medi%C3%A7%C3%A3o-refinado
[Métricas de Processo]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#m%C3%A9tricas-de-processo
[Métricas de Código]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#m%C3%A9tricas-de-c%C3%B3digo
