### ISSUE TITLE
Auditoria Backlog da Release Refinado - 1

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-GQA#32]
Auditoria do Backlog da Release Refinado.

No entendimento do auditor, para se observar se a atividade de [Revisar][revisar] do processo foi realizada, deve-se auditar seu produto, que é o [Backlog da Release Refinado][backlog-da-release-refinado]. Como o objetivo é refinar o backlog, eu entendo que deve ser feita a revisão para identificar o que não foi feito e o porque, para que sejam identificadas as dívidas e feita uma repriorização deste backlog. Desta forma, foram seguidos os [critérios][criterios] que tem como objetivo avaliar se a revisão foi feita, de maneira a possibilitar o refinamento do backlog.

[criterios]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog-da-release-refinado
[revisar]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2114-revisar
[backlog-da-release-refinado]:https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2114-revisar

**Comment by Rdlenke** [comment]
O resultado da auditoria pode ser encontrada no seguinte [Zelda][backlog-da-release-refinado].

[backlog-da-release-refinado]:https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Backlog-da-Sprint-Refinado---Ciclo-1

**Comment by maugustoo** [comment]
O zelda para o resultado da auditoria está errado, o correto é [esse](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Backlog-da-Release-Refinado---Ciclo-1).

**Comment by Rdlenke** [comment]
@maugustoo Bem notado. Obrigado.
