### ISSUE TITLE
Auditoria de Medição e Análise

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#36]
A auditoria da **Medição e Análise** foi feita com base nos [critérios pré-estabelecidos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#medi%C3%A7%C3%A3o-e-an%C3%A1lise) para verificar se o subprocesso está sendo realizado conforme previsto.
O resultado da auditoria pode ser acessado  [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-da-Medi%C3%A7%C3%A3o-e-An%C3%A1lise-do-Ciclo-1).

**Comment by thiagonf** [comment]
A issue não está linkada a uma milestone.

Analisando a auditoria de medição e analise foi possível constatar que a auditoria seguiu o que foi planejado previamente em seu template. Os resultados apontados na auditoria estão corretos e não conformidade apontada de fato é algo que impacta e precisa ser corrigido.
