### ISSUE TITLE
Auditoria do Subprocesso de Desenvolvimento

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#42]
A auditoria do **Subprocesso de Desenvolvimento** foi feita com base nos [critérios pré-estabelecidos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#subprocesso-desenvolvimento) para verificar se o subprocesso está sendo realizado conforme previsto.
O resultado da auditoria pode ser acessado  [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-do-Subprocesso-de-Desenvolvimento-Ciclo-1).

**Comment by fabiolamfleury** [comment]
@joaopaulonsoares Bem observado,valeu. Fixed

**Comment by thiagonf** [comment]
A issue não está linkada a uma milestone.

Analisando a auditoria de subprocesso de desenvolvimento foi possível constatar que a auditoria seguiu o que foi planejado previamente em seu template. As não conformidades apontadas na auditoria são relevantes e devem ser corrigidos
