### ISSUE TITLE
Auditoria - Lista informal de requisitos - 1

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#44]
A auditoria da [Lista informal de requisitos](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2211-elicitar-requisitos) foi feita com base nos [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#lista-informal-de-requisitos) pré-estabelecidos para verificar se a atividade de Elicitar Requisitos aconteceu. 

O resultado da auditoria pode ser acessado através da seguinte página: [Auditoria - Lista informal de requisitos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Lista-informal-de-requisitos---Ciclo-1).

**Comment by Rdlenke** [comment]
Achei curioso o uso da coluna de evidências na tabela do checklist. Acredito que seja contraditório tentar evidenciar que algo não aconteceu.

**Comment by AllanNobre** [comment]
Entendo, a evidência seria para mostrar em que período o artefato não foi encontrado, para evitar possíveis dados não coerentes após a data da auditorias.
