### ISSUE TITLE
Auditoria Backlog Validado - 1

### ISSUE THREAD

**Issue by thiagonf** [UnbFeelings/unb-feelings-GQA#45]
### Auditoria Backlog Validado - 1

O Backlog Validado foi auditado os resultados podem ser visualizados [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Backlog-Validado---Ciclo-1).

**Comment by Ronyell** [comment]
Não Conformidades:

- Link da auditoria na issue quebrado
- Não definiu milestone
- Não assinou issue

O restante parece estar coerente

**Comment by thiagonf** [comment]
Corrigido todas os levantamentos apontados pelo auditor Ronyell Taí
