### ISSUE TITLE
Auditoria - Documentação da Análise das Métricas - 1

### ISSUE THREAD

**Issue by joaopaulonsoares** [UnbFeelings/unb-feelings-GQA#47]
A auditoria da [Documentação da Análise das Métricas](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#315-atividade-analisar-m%C3%A9tricas) foi feita com base nos [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#documenta%C3%A7%C3%A3o-da-an%C3%A1lise-das-m%C3%A9tricas) pré-estabelecidos para verificar se a atividade de Analisar métricas aconteceu. 

O resultado da auditoria pode ser acessado através da seguinte página: [Auditoria - Documentação da Análise de Métricas](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-da-Documenta%C3%A7%C3%A3o-da-An%C3%A1lise-das-M%C3%A9tricas-Ciclo-1).

**Comment by igor-gme** [comment]
A auditoria está coerente, pois está respeitando e seguindo as políticas e templates propostos pela equipe.
