### ISSUE TITLE
Auditoria - Requisitos - 1

### ISSUE THREAD

**Issue by AllanNobre** [UnbFeelings/unb-feelings-GQA#49]
A auditoria daos [Requisitos](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#2212-analisar-requisitos) foi feita com base nos [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#requisitos) pré-estabelecidos para verificar se a atividade de Analisar Requisitos aconteceu. 

O resultado da auditoria pode ser acessado através da seguinte página: [Auditoria - Requisitos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Requisitos-Ciclo-1).

**Comment by Rdlenke** [comment]
Revisado. Parece OK.
