### ISSUE TITLE
Auditoria - Subprocesso de Requisitos

### ISSUE THREAD

**Issue by freemanpivo** [UnbFeelings/unb-feelings-GQA#51]
A documentação da auditoria (Ciclo 2) está sendo realizada nesse [link](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-do-Subprocesso-de-Requisitos---Ciclo-2).

**Comment by freemanpivo** [comment]
Não foi realizada a abertura de issue no repositório de [Documentação](https://github.com/UnbFeelings/unb-feelings-docs/issues), pois as não conformidades dessa auditoria reforçam as mesmas não conformidades de outras auditorias **previamente executadas** (ausência de backlogs e lista informal de requisitos) que podem ser encontradas nessas issues [#9](https://github.com/UnbFeelings/unb-feelings-docs/issues/9), [#10](https://github.com/UnbFeelings/unb-feelings-docs/issues/10) e [#26](https://github.com/UnbFeelings/unb-feelings-docs/issues/26), respectivamente.

**Comment by Ronyell** [comment]
Não Conformidades:

- Checklist não segue o template definido

O restante parece estar coerente.
