### ISSUE TITLE
Auditoria Processo do Ciclo de Desenvolvimento

### ISSUE THREAD

**Issue by freemanpivo** [UnbFeelings/unb-feelings-GQA#52]
A documentação da auditoria (Ciclo 2) está sendo realizada nesse [link](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Processo-do-Ciclo-de-Desenvolvimento---Ciclo-2).

**Comment by Ronyell** [comment]
Não Conformidades:

- Checklist não segue o template definido

O restante parece estar coerente.
