### ISSUE TITLE
Auditoria - Plano de medição refinado - 1

### ISSUE THREAD

**Issue by maugustoo** [UnbFeelings/unb-feelings-GQA#53]
Auditoria do Plano de medição refinado

Para auditar o plano de medição refinado gerado pela atividade [definir medições](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#312-atividade-definir-medi%C3%A7%C3%B5es) do [processo de medição e análise](https://github.com/UnbFeelings/unb-feelings-docs/wiki/Processo#3-processo-de-medi%C3%A7%C3%A3o-e-an%C3%A1lise), serão usados os [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#plano-de-medi%C3%A7%C3%A3o-refinado) previamente definidos para criar o checklist de avaliação desta atividade.

Os resultados da auditoria poderão ser visualizados [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-do-plano-de-medi%C3%A7%C3%A3o-refinado---1).

**Comment by igor-gme** [comment]
A auditoria está coerente, pois está respeitando e seguindo as políticas e templates propostos pela equipe.
