### ISSUE TITLE
Auditoria - Relatório Final - 1

### ISSUE THREAD

**Issue by JonathanRufino** [UnbFeelings/unb-feelings-GQA#55]
A auditoria do **Relatório Final** foi feita com base nos [critérios pré-estabelecidos](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Critérios-de-Avaliação-e-Técnicas-de-Auditoria#relatório-final) para verificar se o documento foi elaborado e se o conteúdo está de acordo com o previsto.
O resultado da auditoria pode ser acessado na página: [Resultado da Auditoria](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Relatório-Final-Ciclo-1).

**Comment by Rdlenke** [comment]
Esta auditoria não era necessária porque este artefato só é gerado no fim do semestre. Portanto, ela será fechada.
