### ISSUE TITLE
Lista informal de Requisitos

### ISSUE THREAD

**Issue by gag2502** [UnbFeelings/unb-feelings-GQA#64]

**Comment by eliseuegewarth** [comment]
A lista informal dos requisitos relacionada ao Backlog da Release 2 foi gerada e disponibilizada através do link https://drive.google.com/drive/folders/1rM5C16fqk0GZhVcly-Jybytd3J8so-aY e foi devidamente anexada ao Backlog da Release 2.

**Comment by eliseuegewarth** [comment]
O Resultado desta auditoria pode ser encontrado [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Lista-informal-de-requisitos-Ciclo-2).
