### ISSUE TITLE
Definir estrutura de organização de não conformidades

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#7]
O TEMPLATE GERADO NESSA ISSUE SOBRE A INCONFORMIDADE DEVE SER ACOPLADO NO TEMPLATE DO RESULTADO DA AUDITORIA;

Definir:
- Como as inconformidades(não conformidades) serão comunicadas e registradas? Issues?
- Montar um template com pelo menos as seguintes informações das não conformidades que devem ser registradas:
  * Qual é a não conformidade?
  * Qual a sua complexidade? (Os tipos de complexidade e o prazo que será dado para tais devem estar definidos nas políticas, exemplo: Não conformidades altas precisam de 3x dias pra resolver, médias 2x dias, baixas x dias
   * Sugestão de melhoria
   * Data final para adequação da não conformidade, lembrando que caso essa data não seja cumprida, a alta gerência deve ser imediatamente avisada

PS: Os termos inconformidades e não conformidades são intercambiáveis, mas a professora prefere o segundo.

**Comment by JonathanRufino** [comment]
Posso fazer essa

**Comment by Rdlenke** [comment]
@fabiolamfleury Será definido um template pra cada inconformidade, ou será um template genérico?

**Comment by AllanNobre** [comment]
@Rdlenke Acredito que teremos um template de resultado da autoria, nesse template deve ter uma sessão de não conformidade que de seguir o mesmo padrão pra cada  Não conformidade encontrada. caso tenha mais de uma será somente mais um tópico com o mesmo template usado pra anterior. Verifique com o restante da equipe tbm.

**Comment by Rdlenke** [comment]
Seria algo como #23, ou algo mais genérico e detalhado?
