### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by gag2502** [UnbFeelings/unb-feelings-GQA#70]

**Comment by Jefersonalves** [comment]
### Auditoria Backlog

O Backlog foi auditado com base nos [critérios](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Crit%C3%A9rios-de-Avalia%C3%A7%C3%A3o-e-T%C3%A9cnicas-de-Auditoria#backlog) definidos. Os resultados podem ser visualizados [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Backlog-Itera%C3%A7%C3%A3o-1-Ciclo-2).
