### ISSUE TITLE
Métricas de Processo

### ISSUE THREAD

**Issue by gag2502** [UnbFeelings/unb-feelings-GQA#78]

**Comment by eliseuegewarth** [comment]
O resultado desta auditoria pode ser encontrado [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-M%C3%A9tricas-de-Processo-Ciclo-2).

**Comment by eliseuegewarth** [comment]
Para a finalização dos resultados desta auditoria, é necessária a abertura de não conformidades, pois os seguintes artefatos não foram gerados:
- Especificação de técnicas de coleta de métricas
- Coleta das métricas

**Comment by eliseuegewarth** [comment]
Analisar documento [Políticas de Não Conformidade](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Pol%C3%ADticas-de-N%C3%A3o-Conformidades) para finalizar esta tarefa.
