### ISSUE TITLE
Reorganizar o subprocesso que lida com as não conformidades

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#8]
- Explicitar no processo que a não conformidade deve ser acompanhada por um prazo diferente das auditorias. Por exemplo, o prazo para resolver o problema X é dois dias, e não até a próxima auditoria

- Colocar na descrição da atividade do processo: ao registrar a não conformidade, é necessário informar a complexidade dela

**Comment by maugustoo** [comment]
Essa issue foi fechada pois as atividades que eram para ser feitas nela serão feitas nas issues #10, #16 e #20 .
