### ISSUE TITLE
Processo do ciclo de desenvolvimento

### ISSUE THREAD

**Issue by gag2502** [UnbFeelings/unb-feelings-GQA#84]

**Comment by Jefersonalves** [comment]
O Processo do ciclo de desenvolvimento foi auditado com base nos critérios definidos. Os resultados podem ser visualizados [aqui](https://github.com/UnbFeelings/unb-feelings-GQA/wiki/Auditoria-Processo-do-ciclo-de-desenvolvimento-Itera%C3%A7%C3%A3o-1-Ciclo-2).
