### ISSUE TITLE
Reorganização da parte da wiki de processo

### ISSUE THREAD

**Issue by fabiolamfleury** [UnbFeelings/unb-feelings-GQA#9]
Foi colocado pela professora: difícil distinção entre a definição do processo de trabalho(GQA, o processo geral) e o processo do auditor, existem subprocessos que não cabem em todas as auditorias

Logo, ao documentar na wiki explicitar que o subprocesso "Programar auditoria" ocorrerá apenas uma vez, isto é, as outras equipes que assumirão o papel de GQA no futuro não terão de realizá-la.

**Comment by maugustoo** [comment]
Essa issue foi fechada pois as atividades que eram para ser feitas nela serão feitas na issue #16
